env:
   global:
     - CONAN_REFERENCE: "llvm/7.0.0"
     - CONAN_USERNAME: "sunxfancy"
     - CONAN_LOGIN_USERNAME: "sunxfancy"
     - CONAN_CHANNEL: "ci"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/elite-lang/ECDK"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.5.2"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
   
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3 
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0

before_install:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - conan remote add sunxfancy https://api.bintray.com/conan/sunxfancy/common 
  - conan user -p ${CONAN_PASSWORD} -r sunxfancy sunxfancy

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh